import {
  IconAperture,
  IconCopy,
  IconLayoutDashboard,
  IconLogin,
  IconMoodHappy,
  IconTypography,
  IconUserPlus,
} from "@tabler/icons-react";

import { uniqueId } from "lodash";

const Menuitems = [
  {
    navlabel: true,
    subheader: "Home",
  },

  {
    id: uniqueId(),
    title: "Trang chủ",
    icon: IconLayoutDashboard,
    href: "/dashboard",
  },
  {
    id: uniqueId(),
    title: "Dashboard",
    icon: IconLayoutDashboard,
    href: "/thongke",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý người dùng",
    icon: IconLayoutDashboard,
    href: "/nguoidung",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý banner",
    icon: IconLayoutDashboard,
    href: "/banner",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý nhà cung cấp",
    icon: IconLayoutDashboard,
    href: "/nhacungcap",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý bài đăng",
    icon: IconLayoutDashboard,
    href: "/baidang",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý thương hiệu",
    icon: IconLayoutDashboard,
    href: "/thuonghieu",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý danh mục",
    icon: IconLayoutDashboard,
    href: "/danhmuc",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý shipper",
    icon: IconLayoutDashboard,
    href: "/shipper",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý hình ảnh",
    icon: IconLayoutDashboard,
    href: "/crudhinhAnh",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý thương hiệu",
    icon: IconLayoutDashboard,
    href: "/thuonghieu",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý đơn hàng",
    icon: IconLayoutDashboard,
    href: "/donhang",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Typography",
    icon: IconTypography,
    href: "/ui/typography",
    roles: ["User"],
  },
  {
    id: uniqueId(),
    title: "Quản lý nhập hàng",
    icon: IconTypography,
    href: "/nhaphang",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý đánh giá",
    icon: IconTypography,
    href: "/danhgia",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý kho",
    icon: IconTypography,
    href: "/kho",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý sản phẩm",
    icon: IconTypography,
    href: "/sanpham",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý Voucher",
    icon: IconTypography,
    href: "/voucher",
    roles: ["Nhân viên kinh doanh", "Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Settings",
    icon: IconTypography,
    href: "/settings",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Response",
    icon: IconTypography,
    href: "/response",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Duyệt sản phẩm",
    icon: IconTypography,
    href: "/xetduyetsanpham",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý popup",
    icon: IconTypography,
    href: "/popup",
    roles: ["Admin"],
  },
];

export default Menuitems;
